---
- hosts: red_team
  become: true
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
    - name: Install system dependencies
      apt:
        name: "{{ item }}"
        state: present
      with_items:
        - build-essential
        - python3-pip
        - python3-dev
        - git
        - curl
        - wget
        - tar
        - python3-venv
        - libssl-dev
        - libffi-dev
        - openssh-client
        - openssh-server
        - openssl
        - jq

    - name: Download and run Node.js setup script
      get_url:
        url: https://deb.nodesource.com/setup_14.x
        dest: /tmp/setup_14.sh
      become: true

    - name: Run the Node.js setup script
      command: bash /tmp/setup_14.sh
      become: true

    - name: Install Node.js and npm
      apt:
        name: nodejs
        state: present
      become: true


    - name: Install networking and reconnaissance tools
      apt:
        name: "{{ item }}"
        state: present
      with_items:
        - nmap
        - netcat
        - nikto
        - gobuster
        - recon-ng
        - net-tools

    - name: Install Amass
      shell: |
        curl -s https://api.github.com/repos/OWASP/Amass/releases/latest \
        | grep "browser_download_url.*linux_amd64.zip" \
        | cut -d : -f 2,3 \
        | tr -d \" \
        | wget -qi -
        unzip amass_linux_amd64.zip
        sudo mv amass_linux_amd64/amass /usr/local/bin/
        rm -rf amass_linux_amd64*

    - name: Install Metasploit Framework
      shell: |
        curl https://raw.githubusercontent.com/rapid7/metasploit-framework/master/msfinstall -o msfinstall
        chmod +x msfinstall
        sudo ./msfinstall
        rm msfinstall

    - name: Install Empire
      shell: |
        git clone https://github.com/EmpireProject/Empire.git
        cd Empire
        ./setup/install.sh

    # - name: Install BloodHound
    #   shell: |
    #     rm -rf BloodHound
    #     git clone https://github.com/BloodHoundAD/BloodHound.git
    #     cd BloodHound
    #     npm install

    - name: Install Social Engineering Toolkit
      shell: |
        git clone https://github.com/trustedsec/social-engineer-toolkit.git
        cd social-engineer-toolkit
        pip3 install -r requirements.txt
        python3 setup.py 

    - name: Install Hydra
      apt:
        name: hydra
        state: present

    # - name: Install KingPhisher # he need sudo privileges
    #   shell: |
    #     wget -q https://github.com/securestate/king-phisher/raw/master/tools/install.sh && \
    #       bash ./install.sh

    # - name: Install Atomic Red Team
    #   shell: |
    #     git clone https://github.com/redcanaryco/atomic-red-team.git
    #     cd atomic-red-team
    #     sudo ./setup.sh

    # - name: Install LinPEAS
    #   shell: |
    #     git clone https://github.com/carlospolop/PEASS-ng.git
    #     cd PEASS-ng/linPEAS
    #     chmod +x linpeas.sh

    # - name: Install GTFOBins
    #   shell: git clone https://github.com/GTFOBins/GTFOBins.github.io.git

    - name: Install Linux Exploit Suggester
      shell: wget https://raw.githubusercontent.com/mzet-/linux-exploit-suggester/master/linux-exploit-suggester.sh -O les.sh

    # - name: Install OWASP ZAP
    #   apt:
    #     name: zaproxy
    #     state: present

    - name: Install SQLMap
      apt:
        name: sqlmap
        state: present

    # - name: Install Covenant
    #   shell: |
    #     git clone https://github.com/cobbr/Covenant.git
    #     cd Covenant
    #     dotnet build

    - name: Install miscellaneous tools
      apt:
        name: "{{ item }}"
        state: present
      with_items:
        - hashcat
        - john
        - wireshark
    
    - name: ADD Users to Red_Team
      shell: |
        git clone https://github.com/zokevlar98/script_cyber_range
        cd /home/ubuntu/script_cyber_range
        sudo chmod +x script_adduser.sh
        sudo ./script_adduser.sh
        # rm script_adduser.sh
  
    - name: Install atomic-red-team 
      shell: |
        git clone https://github.com/zokevlar98/Web_Terminal
        cd /home/ubuntu/Web_Terminal
        sudo git pull --force
        sudo chmod +x script_atomic.sh
        sudo ./script_atomic.sh

    # - name: check instalation and configuration of Red_Team
    #   shell: |
    #     cd /home/ubuntu/script_cyber_range/red_team
    #     sudo chmod +x check.sh
    #     sudo ./check.sh

    - name: Update and upgrade system
      shell: |
        sudo apt update && sudo apt upgrade -y