---
- hosts: red_team
  become: true
  tasks:
    - name: Install system dependencies
      apt:
        name: "{{ item }}"
        state: present
      with_items:
        - build-essential
        - python3-pip
        - python3-dev
        - git
        - curl
        - python3-venv
        - libssl-dev
        - libffi-dev
        - openssh-client
        - openssh-server
        - openssl

    - name: Install networking and reconnaissance tools
      apt:
        name: "{{ item }}"
        state: present
      with_items:
        - nmap
        - netcat
        - nikto
        - amass
        - gobuster
        - recon-ng

    - name: Install Metasploit Framework
      shell: curl https://raw.githubusercontent.com/rapid7/metasploit-framework/master/msfinstall | sudo bash

    - name: Install Empire
      shell: |
        git clone https://github.com/EmpireProject/Empire.git
        cd Empire
        ./setup/install.sh

    - name: Install BloodHound
      shell: |
        git clone https://github.com/BloodHoundAD/BloodHound.git
        cd BloodHound
        npm install

    - name: Install Social Engineering Toolkit
      apt:
        name: set
        state: present

    - name: Install KingPhisher
      shell: |
        git clone https://github.com/securestate/king-phisher.git
        cd king-phisher
        python3 setup.py install

    - name: Install Evilginx2
      shell: |
        git clone https://github.com/evilhack/evilginx2.git
        cd evilginx2
        ./install.sh

    - name: Install LinPEAS
      shell: |
        git clone https://github.com/carlospolop/PEASS-ng.git
        cd PEASS-ng/linPEAS
        chmod +x linpeas.sh

    - name: Install GTFOBins
      shell: git clone https://github.com/GTFOBins/GTFOBins.github.io.git

    - name: Install Linux Exploit Suggester
      shell: git clone https://github.com/mzet-/linux-exploit-suggester.git

    - name: Install OWASP ZAP
      apt:
        name: zaproxy
        state: present

    - name: Install SQLMap
      apt:
        name: sqlmap
        state: present

    - name: Install Covenant
      shell: |
        git clone https://github.com/cobbr/Covenant.git
        cd Covenant
        dotnet build

    - name: Install miscellaneous tools
      apt:
        name: "{{ item }}"
        state: present
      with_items:
        - hashcat
        - john
        - wireshark

    - name: Update and upgrade system
      shell: |
        sudo apt update && sudo apt upgrade -y
        pip list --outdated | awk 'NR>2 {print $1}' | xargs pip install --upgrade